#自动调用api保活，加密版
name: Auto Api Secret

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 */6 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Pull gist
      env:
        GIST_HTTPS: ${{ secrets.GIST_HTTPS_WITH_TOKEN }}
      run: git clone $GIST_HTTPS
    - name: Test Api #Api调用
      env:
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id 提供
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # secrets_key 提供
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_TEXT: ${{ secrets.GIST_TEXT }}
      run: |
        python 1.py
    - name: Push Gist #上传新的refresh_token到仓库
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name AutoupdateRobot
        cd $GIST_ID
        git add .
        git commit -m '更新 token'
        git remote -v
        git push origin master
